INSERT INTO CATAGORY (DESCRIPTION) VALUES ('American');
INSERT INTO CATAGORY (DESCRIPTION) VALUES ('Italian');
INSERT INTO CATAGORY (DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATAGORY (DESCRIPTION) VALUES ('Brittish');
INSERT INTO CATAGORY (DESCRIPTION) VALUES ('Asian');
INSERT INTO CATAGORY (DESCRIPTION) VALUES ('Chiniese');
INSERT INTO CATAGORY (DESCRIPTION) VALUES ('Ukrainian');
insert into Mesurements (DESCRIPTION) values ('Tea Spoon');
insert into Mesurements (DESCRIPTION) values ('Cup');
insert into Mesurements (DESCRIPTION) values ('Pinch');
insert into Mesurements (DESCRIPTION) values ('Grams');
insert into Mesurements (DESCRIPTION) values ('ml');
insert into Mesurements (DESCRIPTION) values ('Liter');
insert into Mesurements (DESCRIPTION) values ('Kg');
insert into Mesurements (DESCRIPTION) values ('Each');